---
- name: Config IP and join domain
  hosts: all
  gather_facts: no
  become: no
  
  vars_prompt:
    - name: "base_dir"
      prompt: "\e[32mPlease the config file directory\e[0m"
      private: no

    - name: "config_file"
      prompt: "\e[32mPlease type the VM config file name (without '.yml')\e[0m"
      private: no

  vars_files:
    - myvault.yml

  tasks:
  
    - name: Ensure --limit is specified
      fail:
        msg: "❌ No --limit specified! Please use --limit <target>"
      when: ansible_limit is not defined or ansible_limit == "all"

    - name: Dynamically include the specific XenServer vars file
      include_vars: "{{ base_dir }}/{{ config_file }}.yml"
      delegate_to: localhost
      tags: domain
    
    - name: Set static IP address
      win_shell: |
        # Retrieve the network adapter that is currently up
        $adapter = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' }
        $interfaceAlias = $adapter.Name

        # Remove existing IP addresses
        Get-NetIPAddress -InterfaceAlias $interfaceAlias -AddressFamily IPv4 | Remove-NetIPAddress -Confirm:$false

        # Remove existing routes
        Get-NetRoute -InterfaceAlias $interfaceAlias -AddressFamily IPv4 | Remove-NetRoute -Confirm:$false

        # Assign the new static IP address and set the default gateway
        New-NetIPAddress -InterfaceAlias $interfaceAlias -IPAddress '{{ vm_ip }}' -PrefixLength 24 -DefaultGateway '{{ vm_gateway }}'

        # Set the DNS server address
        Set-DnsClientServerAddress -InterfaceAlias $interfaceAlias -ServerAddresses '{{ vm_dns }}'
      async: 1
      poll: 0

    - name: Update ansible_host variable
      set_fact:
        ansible_host: '{{ vm_ip }}'
      tags: domain

    - name: Wait for the server to become reachable
      wait_for_connection:
        delay: 10
        timeout: 300
        sleep: 10

    - name: Rename the server
      ansible.windows.win_hostname:
        name: '{{ vm_hostname }}'
      register: rename
    
    - name: Reboot after renaming 
      ansible.windows.win_reboot:
      when: rename.reboot_required

    - name: Wait for the server to become reachable
      wait_for_connection:
        delay: 10 
        timeout: 300 
        sleep: 10 

    - name: Join the server to the domain
      ansible.windows.win_domain_membership:
        dns_domain_name: 'testlab.com'
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
      register: domain_join
      tags: domain

    - name: Reboot after domain join
      ansible.windows.win_reboot:
      when: domain_join.reboot_required
      tags: domain

    - name: Wait for the server to become reachable
      wait_for_connection:
        delay: 10 
        timeout: 300 
        sleep: 10
      tags: domain

    - name: All done
      debug:
        msg: "Your vm is ready to use"
      tags: domain
